### ISSUE TITLE
Post-User Registration

### ISSUE THREAD

**Issue by aenyeart** [event-egg/event-egg-server#1]

**Comment by aenyeart** [comment]
![image](https://user-images.githubusercontent.com/65784446/146653660-273bcbce-793a-43bc-acb7-2722c0459d29.png)
Post User Registration
This hook allows custom actions to be executed after a new user has been created in the database. It executes asynchronously with the rest of the Auth0 pipeline and its outcome does not affect the Auth0 transaction.

**Comment by daniel-jacks** [comment]
Here is the full documentation https://auth0.com/docs/hooks/extensibility-points/post-user-registration, definitely will be nice to execute a DB post() or something with user information from what I can gather, immediately after they log in. We may want to set it up synchronously after the user sets up their profile but we can discuss tmrw. I'm thinking, if we set it up synchronously, we await axious.get(<user data link or something>), and then proceed with giving them filtered data based on preference?
