### ISSUE TITLE
Auth0 implementation

### ISSUE THREAD

**Issue by aenyeart** [event-egg/event-egg-server#20]
Implement Auth0 
- [x] Get our account configured on auth0's website
- [x] Add auth.js module containing verifyUser function
- [x] ![image](https://user-images.githubusercontent.com/65784446/146984528-c054aa34-a5ea-474c-b057-a03268e8a61c.png)
- [x] require verifyUser into modules
- [x] incorporate authentication into necessary functions
- [x] ![image](https://user-images.githubusercontent.com/65784446/146984802-4d53fc20-e8b0-4404-84dc-008395e5c4bf.png)

**Comment by Kellen-Linse** [comment]
Authentication tests have to be done in tandem with front end, so we are holding off on the rest until we can work as a full team.
